AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  {{lambda-name}}:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 60
      Tracing: "Active"
      MemorySize: 3008
      Handler: not.used
      Runtime: provided
      CodeUri: function.zip
      Policies:
        - AWSLambdaExecute

  {{lambda-name}}Logs:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${ {{lambda-name}} }
      RetentionInDays: 1
